name: CI

on: push

jobs:
    build:
        runs-on: windows-latest
        env:
          SLN_FILE_PATH: "src/Shaolinq.sln"
          SHAOLINQ_TESTS_SQLSERVER_HOST: localhost
          SHAOLINQ_TESTS_SQLSERVER_USERNAME: sa
          SHAOLINQ_TESTS_SQLSERVER_PASSWORD: r00t_p@$w0rd1
        steps:
            - name: Chekout code
              uses: actions/checkout@v2

            - name: Setup MSBuild Path
              uses: warrenbuckley/Setup-MSBuild@v1

            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.2
             
            - name: Restore NuGet Packages
              run: nuget restore src/Shaolinq.sln
         
            - name: Build Solution
              run: msbuild src/Shaolinq.sln /p:Configuration=Release -m

            - name: Bring the docker-compose stack up
              run: docker-compose  -f ./tests/docker-compose.yaml up -d

            - name: Check running containers
              run: docker ps -a