name: CI

on: push

jobs:
    ci_build:
        name: Build and Test
        runs-on: windows-latest
        env:
          SLN_FILE_PATH: "src/Shaolinq.sln"
          SHAOLINQ_TESTS_SQLSERVER_HOST: localhost
          SHAOLINQ_TESTS_SQLSERVER_USERNAME: sa
          SHAOLINQ_TESTS_SQLSERVER_PASSWORD: r00t_p@$w0rd1
        steps:
            - name: Chekout code
              uses: actions/checkout@v2

            - name: Setup MSBuild Path
              uses: warrenbuckley/Setup-MSBuild@v1

            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.2
             
            - name: Restore NuGet Packages
              run: nuget restore $Env:SLN_FILE_PATH
         
            - name: Build Solution
              run: msbuild -nologo -verbosity:q $Env:SLN_FILE_PATH /p:Configuration=Release -m 

            - name: Download NUnitConsole Runner To Workspace
              uses: carlosperate/download-file-action@v1.0.3
              with:
                file-url: https://github.com/nunit/nunit-console/releases/download/v3.11.1/nunit-console-runner.3.11.1.nupkg
                file-name: nunit-console.zip

            - name: Decompress console
              uses: Amadevus/pwsh-script@v2
              with: 
                script: "Expand-Archive -Path nunit-console.zip -DestinationPath $Env:GITHUB_WORKSPACE/nunit"

            - name: Bring the docker-compose stack up
              run: docker-compose  -f ./tests/docker-compose.yaml up -d

            - name: Check running containers
              run: docker ps -a

            - name: Run Unit-Tests
              run: ./nunit/tools/nunit3-console.exe ./tests/Shaolinq.Tests/bin/Release/Shaolinq.Tests.dll ./tests/Shaolinq.AsyncRewriter.Tests/bin/Release/Shaolinq.AsyncRewriter.Tests.dll
